### ISSUE TITLE
CLI Release pre checklist

### ISSUE THREAD

**Issue by andreespirela** [three-em/3em#50]
- [x] Compatible with Smartweave
    - [x] https://github.com/3distributed/3em/issues/47
- [x] Supports EVM
    - [x] https://github.com/3distributed/3em/issues/28
- [x] https://github.com/3distributed/3em/issues/27
- [x] https://github.com/3distributed/3em/issues/29
- [x] https://github.com/3distributed/3em/issues/42
- [x] Write Web Assembly tests for multiple languages
    - Refer to https://stackoverflow.com/questions/43540878/what-languages-can-be-compiled-to-webassembly-wasm to see what languages can be compiled
    - https://github.com/3distributed/3em/issues/48
- [x] https://github.com/3distributed/3em/issues/49
- [x] https://github.com/3distributed/3em/issues/52
- [x] https://github.com/3distributed/3em/issues/51
